routes/web.php
<?php

Auth::routes();
Route::group([ 'prefix' => 'dashboard','middleware' =>['auth']],function(){

  Route::get('/','DashboardController@index');
  Route::resource('achats', 'achatsController');
  Route::get('/cl','ClController@index')->name('cl');
  Route::post('/tests/imprimer_credit','CalculeController@imprimer');
  Route::get('/imprimer','VenteController@imprimer')->name('imprimer');
  Route::resource('produit','produitController');
  Route::get('/users','CalculeController@showtotal')->name('users');
  Route::resource('achatdiver','AchatdiverController');
  Route::get('/search','CalculeController@search');
  Route::resource('Vente','VenteController');
  Route::get('/rnt','CalculeController@zero');
  Route::resource('produit_vente','produit_venteController');
  Route::get('/putzero/{id}','CalculeController@puttozero')->name('putzero');
  Route::post('/tests/{id}/add_produit_divers','CalculeController@add_produit_divers');
  
  Route::get('/cherchez','VenteController@cherchez')->name('cherchez');
  Route::get('/putzer/{id}','CalculeController@puttozer')->name('putzero1');
  Route::get('/putze/{id}','CalculeController@puttozer1')->name('putzero2');

  Route::get('/vente_users','CalculeController@showtota')->name('vente_users');
  Route::get('/caisse','CalculeController@showcaisse')->name('caisse');
  Route::post('/tests/{test_id}/add_produit','CalculeController@add_divers');
  
  Route::get('/tests/{test_id}/get_produit','CalculeController@get_divers');
  
  Route::post('/tests/upd_produit','CalculeController@upd_produit');

  Route::post('/tests/{test_id}/upd_credit','CalculeController@upd_credit');
  
  Route::get('/tests/{test_id}/get_produit_divers','CalculeController@get_produit_divers');
  
  
  Route::get('/tests/{test_id}/get_achats','CalculeController@get_achats');
  Route::post('/tests/{test_id}/add_achats','CalculeController@add_achats');
  Route::post('/tests/upd_achats','CalculeController@upd_achats');
  

  
});  

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.home');
    }
}

resources/views/dashboard/partials/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-inner">
        <!-- ### $Sidebar Header ### -->
        <div class="sidebar-logo">
            <div class="peers ai-c fxw-nw">
                <div class="peer peer-greed">
                    <a class='sidebar-link td-n' href="/dashboard" class="td-n">
                        <div class="peers ai-c fxw-nw">
                            <div class="peer">
                                <div class="logo">
                                    <img src="/images/gva_logo_small.png" style="width: 70%; height: auto; padding: 10px" alt="">
                                </div>
                            </div>
                            <div class="peer peer-greed">
                                <h5 class="lh-1 mB-0 logo-text">Vge</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="peer">
                    <div class="mobile-toggle sidebar-toggle">
                        <a href="" class="td-n">
                            <i class="ti-arrow-circle-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- ### $Sidebar Menu ### -->
        <ul class="sidebar-menu scrollable pos-r">
            <li class="nav-item mT-15 active">
                <a class='sidebar-link' href="/dashboard" default>
					<span class="icon-holder">
						<i class="c-blue-500 ti-home"></i>
					</span>
                    <span class="title">Dashboard</span>
                </a>
            </li>
            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('achats.index') }}" default>
					<span class="icon-holder">
						<i class="c-red-500 ti-file"></i>
					</span>
                    <span class="title">Achats</span>
                </a>

            </li>
            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('achatdiver.index') }}" default>
                    <span class="icon-holder">
                        <i class="c-red-500 ti-file"></i>
                    </span>
                    <span class="title">Achats divers</span>
                </a>

            </li>
            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('users') }}" default>
                    <span class="icon-holder">
                        <i class="c-red-500 ti-file"></i>
                    </span>
                    <span class="title">Consulter les Transaction</span>
                </a>

            </li>
            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('Vente.index') }}" default>
					<span class="icon-holder">
						<i class="c-green-500 ti-user"></i>
					</span>
                    <span class="title">Vente</span>
                </a>
            </li>

            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('vente_users') }}" default>
                    <span class="icon-holder">
                        <i class="c-green-500 ti-user"></i>
                    </span>
                    <span class="title">Statistiques</span>
                </a>
            </li>

            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('caisse') }}" default>
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-volume"></i>
                    </span>
                    <span class="title">caisse</span>
                </a>
            </li>

            <li class="nav-item mT-15 ">
                <a class='sidebar-link' href="{{ route('cl') }}" default>
                    <span class="icon-holder">
                        <i class="c-blue-500 ti-volume"></i>
                    </span>
                    <span class="title">état des créances</span>
                </a>
            </li>

        </ul>
    </div>
</div>

resources/views/dashboard/partials/spinner.blade.php
<!-- @Page Loader -->
<!-- =================================================== -->
<div id='loader'>
    <div class="spinner"></div>
</div>

<script type="text/javascript">
    window.addEventListener('load', () => {
    const loader = document.getElementById('loader');
    setTimeout(() => {
        loader.classList.add('fadeOut');
    }, 300);
    });
</script>

resources/views/dashboard/partials/topbar.blade.php
<div class="header navbar">
	<div class="header-container">
		<ul class="nav-left">
			<li>
				<a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
					<i class="ti-menu"></i>
				</a>
			</li>
			<li class="search-box">
				<a class="search-toggle no-pdd-right" href="javascript:void(0);">
					<i class="search-icon ti-search pdd-right-10"></i>
					<i class="search-icon-close ti-close pdd-right-10"></i>
				</a>
			</li>
			<li class="search-input">
				<input    id="search1" name="search1" type="text" placeholder="Search...">
				<input  id="search3" name="search3"  type="text" placeholder="Search...">
				<select  size="1"  id="search2" name="search2" >
					<option value="Vente">Vente</option>
					<option value="Achat">Achat</option>	
				</select>	
			</li>
		</ul>
		<ul class="nav-right">
			<li class="notifications dropdown">
				<span class="counter bgc-red">1</span>
				<a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
					<i class="ti-bell"></i>
				</a>

				<ul class="dropdown-menu">
					<li class="pX-20 pY-15 bdB">
						<i class="ti-bell pR-10"></i>
						<span class="fsz-sm fw-600 c-grey-900">Notifications</span>
					</li>
					<li>
						<ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
							<li>
								<a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
									<div class="peer mR-15">
										<img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
									</div>
									<div class="peer peer-greed">
										<span>
											<span class="fw-500">John Doe</span>
											<span class="c-grey-600">liked your
												<span class="text-dark">post</span>
											</span>
										</span>
										<p class="m-0">
											<small class="fsz-xs">5 mins ago</small>
										</p>
									</div>
								</a>
							</li>
						</ul>
					</li>
					<li class="pX-20 pY-15 ta-c bdT">
						<span>
							<a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications
								<i class="ti-angle-right fsz-xs mL-10"></i>
							</a>
						</span>
					</li>
				</ul>
			</li>

			<li class="dropdown">
				<a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
					<div class="peer mR-10">
						<img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt="">
					</div>
					<div class="peer">
						<span class="fsz-sm c-grey-900">John Doe</span>
					</div>
				</a>
				<ul class="dropdown-menu fsz-sm">
					<li>
						<a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
							<i class="ti-user mR-10"></i>
							<span>Profile</span>
						</a>
					</li>
					<li>
						<form action="/logout" method="POST">
							{{ csrf_field() }}
							<button class="menu-btn d-b td-n pY-5 bgcH-grey-100 c-grey-700">
								<i class="ti-power-off mR-10"></i>
								<span>Logout</span>
							</button>
						</form>
					</li>
				</ul>
			</li>
		</ul>
	</div>
</div>